name: Pylint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # You can specify your desired Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
        pylint_score=$(pylint $(find . -type f -name "*.py") --output-format=parseable | tee pylint_output.txt | grep "Your code has been rated at" | awk '{print $7}' | tr -d '/10.')
        echo "Pylint score: $pylint_score"
