name: Pylint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # You can specify your desired Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
          set -o pipefail
          pylint_output=$(find . -name "*.py" | xargs pylint || true)
          echo "$pylint_output"
          pylint_score=$(echo "$pylint_output" | grep "Your code has been rated at" | awk '{print $7}' | cut -d "/" -f 1)
          echo "Pylint score: $pylint_score"
          if (( $(echo "$pylint_score < 9.0" | bc -l) )); then
            exit 1
          fi
      shell: bash
